lugar([puntarenas]).
lugar([limon]).
lugar([guanacaste]).
lugar([heredia]).
lugar([san_jose]).
lugar([alajuela]).
lugar([cartago]).
edge(alajuela,san_jose,10).
edge(san_jose,alajuela,10).
edge(san_jose,cartago,12).
edge(cartago,san_jose,12).
edge(cartago,limon,20).
edge(limon,san_jose,20).
edge(san_jose,limon,20).
edge(san_jose,heredia,8).
edge(heredia,san_jose,8).
edge(alajuela,guanacaste,30).
edge(guanacaste,alajuela,30).
edge(alajuela,puntarenas,15).
edge(puntarenas,alajuela,15).
edge(san_jose,puntarenas,25).
